version: 2

project_name: ink

builds:
  - id: ink
    main: ./cmd/ink
    binary: ink
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: archives
    ids:
      - ink
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

nfpms:
  - id: deb-packages
    ids:
      - ink
    package_name: ink
    file_name_template: >-
      {{ .PackageName }}_{{ .Version }}_{{ .Arch }}
    vendor: drahil
    homepage: https://github.com/drahil/ink
    maintainer: drahil
    description: A keyboard-first terminal editor for PHP projects.
    formats:
      - deb
    bindir: /usr/bin
    section: editors
    priority: optional

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
